### ISSUE TITLE
'Headline Marquee' module - Joomla - target in a new window...

### ISSUE THREAD

**Issue by masterstf3** [Spudley/mod_headlinemarquee#1]
For the 'Headline Marquee' module, I suggest an option when choosing to use the RSS feed.
When you click on a news item, you should be prompted for a new browser tab.
--- Target in a new window. So, it was perfect. I look forward to this change.  Thanks for listening.
Master STF3

**Comment by Spudley** [comment]
Hi. Thanks for the suggestion. Sounds like a good idea. I think it could easily apply to all types of feed, not just RSS.

**Comment by Spudley** [comment]
This feature has been implemented in [version 2.3.0](https://github.com/Spudley/mod_headlinemarquee/releases/tag/2.3.0), along with a few other new options.

Thank you for your suggestion.
